### ISSUE TITLE
Issue with Client Spoofer

### ISSUE THREAD

**Issue by TejasLamba2006** [xia-mc/Raven-XD#31]
My game crashed with
```java
java.lang.NoClassDefFoundError: keystrokesmod/mixins/impl/network/C17PacketCustomPayloadAccessor
	at keystrokesmod.module.impl.other.ClientSpoofer.onSendPacket(ClientSpoofer.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_122_ClientSpoofer_onSendPacket_SendPacketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.network.NetworkManager.handler$zzb000$sendPacket(NetworkManager.java:2544)
	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java)
	at net.minecraft.client.network.NetHandlerPlayClient.handleJoinGame(NetHandlerPlayClient.java:259)
	at net.minecraft.network.play.server.S01PacketJoinGame.processPacket(SourceFile:76)
	at net.minecraft.network.play.server.S01PacketJoinGame.processPacket(SourceFile:13)
	at keystrokesmod.utility.PacketUtils.receivePacket(PacketUtils.java:46)
	at keystrokesmod.module.impl.player.Backtrack.onPreTick(Backtrack.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_149_Backtrack_onPreTick_PreTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.Minecraft.handler$zzf000$runTickPre(Minecraft.java:3099)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.run(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by xia-mc** [comment]
your mod list?

**Comment by TejasLamba2006** [comment]
> your mod list?

![image](https://github.com/xia-mc/Raven-bS/assets/73745640/589c643f-4fbf-44f5-af5d-f39b30df8762)

**Comment by xia-mc** [comment]
A mod is not compatible with clientspoofer, and you may need to fix it yourself

**Comment by TejasLamba2006** [comment]
@xia-mc 
![image](https://github.com/xia-mc/Raven-bS/assets/73745640/80be9aa0-7d95-41ab-b6c6-b1de82461b3e)
server disconnects with reason unexpected pong

**Comment by TejasLamba2006** [comment]
![image](https://github.com/xia-mc/Raven-bS/assets/73745640/3f90bbc8-3eeb-4dc1-9cb2-9ecf4403ecdb)

**Comment by TejasLamba2006** [comment]
happens all the time I kill some1
![image](https://github.com/xia-mc/Raven-bS/assets/73745640/a9b33fc8-fdfc-4357-aee2-3752336582c8)

**Comment by xia-mc** [comment]
what's server? some server has strict backtrack check and you may need to set 'start range' to 0 or set 'stop on hurtttime' to -1.

**Comment by TejasLamba2006** [comment]
Hello @xia-mc,

The server is Pika network, I do have 'stop on hurttime' set to -1

**Comment by xia-mc** [comment]
then set the start range to 0
