### ISSUE TITLE
Crash when mouse button binded with smth

### ISSUE THREAD

**Issue by TejasLamba2006** [xia-mc/Raven-XD#621]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

binding something to middle mouse then printing binds with .binds crashes the game

### Repro steps

1. bind a module to middle mouse button (m2) 
2. go into chat and type .binds

### Raven XD version

1.14.0

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (raven-XD.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/13/24 8:03 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 1002
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at keystrokesmod.utility.Commands.rCMD(Commands.java:327)
	at keystrokesmod.module.impl.client.CommandChat.onSendPacket(CommandChat.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CommandChat_onSendPacket_SendPacketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.network.NetworkManager.handler$sendPacket$zzd000(NetworkManager.java:29)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:720)
	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java:231)
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:448)
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437)
	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at keystrokesmod.utility.Commands.rCMD(Commands.java:327)
	at keystrokesmod.module.impl.client.CommandChat.onSendPacket(CommandChat.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CommandChat_onSendPacket_SendPacketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.network.NetworkManager.handler$sendPacket$zzd000(NetworkManager.java:29)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:720)
	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java:231)
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:448)
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437)
	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiChat

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mumble'/34, l='MpServer', x=-242.70, y=12.00, z=762.42]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -240.00,4.00,885.00 - World: (-240,4,885), Chunk: (at 0,0,5 in -15,55; contains blocks -240,0,880 to -225,255,895), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 251889 game time, 251889 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntitySheep['Sheep'/16, l='MpServer', x=-175.22, y=4.00, z=711.16], EntityCow['Cow'/17, l='MpServer', x=-172.88, y=4.00, z=720.84], EntityChicken['Chicken'/8, l='MpServer', x=-292.44, y=4.00, z=836.28], EntityPlayerSP['Mumble'/34, l='MpServer', x=-242.70, y=12.00, z=762.42], EntityHorse['Horse'/12, l='MpServer', x=-210.50, y=4.00, z=698.50], EntityHorse['Horse'/15, l='MpServer', x=-190.16, y=4.00, z=780.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_402, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 611711808 bytes (583 MB) / 1775763456 bytes (1693 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -Xverify:none -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCHIJAAAA	keystrokes{KMV5} [KeystrokesMod] (raven-XD.jar) 
	Loaded coremods (and transformers): 
MixinLoader (raven-XD.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.20.30.231108' Renderer: 'AMD Radeon RX 7800 XT'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 7800 XT GL version 4.6.0 Compatibility Profile Context 23.20.30.231108, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 7700X 8-Core Processor
```

**Comment by xia-mc** [comment]
fixed in latest dev branch
