### ISSUE TITLE
Game crashed on bind.

### ISSUE THREAD

**Issue by xia-mc** [xia-mc/Raven-XD#623]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

Game instant crashed on bind a mouse key to any module.

### Repro steps

1. run command `bind Backtrack M2`
2. game crashed.

### Raven XD version

1.14.1 (dev branch)

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (raven-XD.jar)
  CustomSkinLoader ([万用皮肤补丁] CustomSkinLoader_ForgeLegacy-14.17.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. ([泡沫修复] foamfix-0.6.3a-anarchy-1.8.x.jar)
  CameraFMLLoadingPlugin (Camera-1.1-1.8.9.jar)
  LabyModCoreMod (LabyMod-3-1.8.9.jar)
  Glint Colorizer ([1.8.9] GlintColorizer - 1.0.jar)
  InputFix ([输入修正] InputFix-1.8.x-v2.jar)
  DamageTintCoreMod (Damage_Tint_1.2 (F).jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 24-7-14 上午12:22
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at keystrokesmod.Raven.onTick(Raven.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_Raven_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at keystrokesmod.Raven.onTick(Raven.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_Raven_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)

-- Affected level --
Details:
	Level name: MpServer
	All players: 14 total; [EntityPlayerSP['xia__mc'/454150, l='MpServer', x=152.97, y=62.00, z=166.70], EntityOtherPlayerMP['HeathB'/121, l='MpServer', x=132.50, y=62.00, z=182.38], EntityOtherPlayerMP['HeathA'/124, l='MpServer', x=132.22, y=62.00, z=188.00], EntityOtherPlayerMP['MaxRange'/127, l='MpServer', x=135.53, y=62.00, z=185.53], EntityOtherPlayerMP['MinRange'/130, l='MpServer', x=130.50, y=62.00, z=185.41], EntityOtherPlayerMP['LoyisaIsImposter'/454147, l='MpServer', x=181.00, y=60.00, z=151.00], EntityOtherPlayerMP['MovingD'/103, l='MpServer', x=138.01, y=62.00, z=209.34], EntityOtherPlayerMP['MovingA'/106, l='MpServer', x=136.76, y=62.00, z=207.78], EntityOtherPlayerMP['Moving'/115, l='MpServer', x=140.34, y=62.00, z=202.62], EntityOtherPlayerMP['Standing'/118, l='MpServer', x=137.94, y=62.00, z=196.22], EntityOtherPlayerMP['MovingC'/109, l='MpServer', x=139.62, y=62.00, z=205.62], EntityOtherPlayerMP['MovingB'/112, l='MpServer', x=140.31, y=62.00, z=207.96], EntityOtherPlayerMP['YoonDD'/454151, l='MpServer', x=164.47, y=62.00, z=179.78], EntityOtherPlayerMP['The_song_of_Saya'/454152, l='MpServer', x=198.08, y=62.00, z=168.68]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 211.00,60.00,162.00 - World: (211,60,162), Chunk: (at 3,3,2 in 13,10; contains blocks 208,0,160 to 223,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 53757 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 143 total; [EntityPlayerSP['xia__mc'/454150, l='MpServer', x=152.97, y=62.00, z=166.70], EntityPig['Pig'/452358, l='MpServer', x=143.38, y=60.00, z=156.56], EntityVillager['DamageTest1'/1, l='MpServer', x=169.50, y=62.00, z=168.50], EntityPig['Pig'/452359, l='MpServer', x=145.22, y=60.00, z=155.25], EntityOtherPlayerMP['YoonDD'/454151, l='MpServer', x=164.47, y=62.00, z=179.78], EntityVillager['DamageTest2'/2, l='MpServer', x=169.50, y=62.00, z=174.50], EntityPig['Pig'/452356, l='MpServer', x=147.53, y=60.00, z=151.18], EntityZombie['NormalKnockBack'/3, l='MpServer', x=161.50, y=62.00, z=176.50], EntityPig['Pig'/452357, l='MpServer', x=148.53, y=60.00, z=152.41], EntityZombie['KnockBack2'/4, l='MpServer', x=158.50, y=62.00, z=172.50], EntityPig['Pig'/452354, l='MpServer', x=141.56, y=60.00, z=154.41], EntityZombie['KnockBack1'/5, l='MpServer', x=161.50, y=62.00, z=168.50], EntityPig['Pig'/452355, l='MpServer', x=148.53, y=60.00, z=154.47], EntityOtherPlayerMP['LoyisaIsImposter'/454147, l='MpServer', x=181.00, y=60.00, z=151.00], EntityZombie['SuperKnockBack'/6, l='MpServer', x=164.50, y=62.00, z=172.50], EntityPig['Pig'/452352, l='MpServer', x=141.47, y=60.00, z=153.09], EntityOtherPlayerMP['HeathB'/121, l='MpServer', x=132.50, y=62.00, z=182.38], EntityPig['Pig'/452353, l='MpServer', x=146.50, y=60.00, z=149.41], EntityOtherPlayerMP['HeathA'/124, l='MpServer', x=132.22, y=62.00, z=188.00], EntityPig['Pig'/452366, l='MpServer', x=143.94, y=60.00, z=151.97], EntityOtherPlayerMP['MaxRange'/127, l='MpServer', x=135.53, y=62.00, z=185.53], EntityPig['Pig'/452367, l='MpServer', x=141.44, y=60.00, z=155.59], EntityOtherPlayerMP['MinRange'/130, l='MpServer', x=130.50, y=62.00, z=185.41], EntityPig['Pig'/452364, l='MpServer', x=140.44, y=60.00, z=154.50], EntityPig['Pig'/452365, l='MpServer', x=143.50, y=60.00, z=155.34], EntityPig['Pig'/452362, l='MpServer', x=142.59, y=60.00, z=148.44], EntityPig['Pig'/452363, l='MpServer', x=142.55, y=60.00, z=149.45], EntityPig['Pig'/452360, l='MpServer', x=142.59, y=60.00, z=155.44], EntityOtherPlayerMP['The_song_of_Saya'/454152, l='MpServer', x=198.08, y=62.00, z=168.68], EntityPig['Pig'/452361, l='MpServer', x=140.44, y=60.00, z=152.13], EntityPig['Pig'/452374, l='MpServer', x=144.00, y=60.00, z=154.19], EntityPig['Pig'/452375, l='MpServer', x=142.79, y=60.00, z=150.69], EntityPig['Pig'/452372, l='MpServer', x=147.34, y=60.00, z=150.66], EntityPig['Pig'/452373, l='MpServer', x=146.00, y=60.00, z=156.53], EntityPig['Pig'/452370, l='MpServer', x=147.56, y=60.00, z=149.47], EntityPig['Pig'/452371, l='MpServer', x=145.22, y=60.00, z=156.53], EntityPig['Pig'/452368, l='MpServer', x=145.53, y=60.00, z=149.44], EntityPig['Pig'/452369, l='MpServer', x=142.00, y=60.00, z=153.78], EntityVillager['Aim5'/382738, l='MpServer', x=191.50, y=65.00, z=134.50], EntityPig['Pig'/452382, l='MpServer', x=142.82, y=60.00, z=150.86], EntityPig['Pig'/452383, l='MpServer', x=143.81, y=60.00, z=149.50], EntityPig['Pig'/452380, l='MpServer', x=146.41, y=60.00, z=155.56], EntityPig['Pig'/452381, l='MpServer', x=142.56, y=60.00, z=156.56], EntityPig['Pig'/452378, l='MpServer', x=147.31, y=60.00, z=152.59], EntityPig['Pig'/452379, l='MpServer', x=143.97, y=60.00, z=153.03], EntityPig['Pig'/452376, l='MpServer', x=145.72, y=60.00, z=148.44], EntityPig['Pig'/452377, l='MpServer', x=141.47, y=60.00, z=151.00], EntityPig['Pig'/452386, l='MpServer', x=144.92, y=60.00, z=154.40], EntityPig['Pig'/452384, l='MpServer', x=146.53, y=60.00, z=156.59], EntityPig['Pig'/452385, l='MpServer', x=144.72, y=60.00, z=151.84], EntityVillager['Aim2'/384034, l='MpServer', x=174.50, y=62.00, z=134.50], EntityLargeFireball['Fireball'/46, l='MpServer', x=169.84, y=66940619.14, z=204.50], EntityLargeFireball['Fireball'/47, l='MpServer', x=168.88, y=66940223.95, z=204.59], EntityLargeFireball['Fireball'/48, l='MpServer', x=167.38, y=66940174.54, z=204.66], EntityLargeFireball['Fireball'/49, l='MpServer', x=167.81, y=66940075.73, z=204.72], EntityVillager['Aim8'/316998, l='MpServer', x=179.50, y=73.50, z=134.50], EntityVillager['Aim1'/234570, l='MpServer', x=169.50, y=62.00, z=134.50], EntityOtherPlayerMP['BestFujian'/454054, l='MpServer', x=171.94, y=60.00, z=145.19], EntityOtherPlayerMP['LoyisaIsImposter'/454147, l='MpServer', x=181.00, y=60.00, z=151.00], EntityVillager['Aim7'/317020, l='MpServer', x=174.50, y=73.00, z=134.50], EntityArmorStand['Armor Stand'/91, l='MpServer', x=211.50, y=145.00, z=215.50], EntityVillager['Aim6'/328793, l='MpServer', x=169.50, y=72.50, z=134.50], EntityArmorStand['Armor Stand'/92, l='MpServer', x=211.50, y=145.00, z=218.50], EntityArmorStand['Armor Stand'/93, l='MpServer', x=210.50, y=145.00, z=218.50], EntitySheep['Sheep'/452708, l='MpServer', x=192.88, y=62.00, z=188.81], EntityOtherPlayerMP['The_song_of_Saya'/454152, l='MpServer', x=198.08, y=62.00, z=168.68], EntityOtherPlayerMP['Harling_Leo'/454116, l='MpServer', x=207.71, y=63.04, z=161.17], EntityOtherPlayerMP['MovingD'/103, l='MpServer', x=138.01, y=62.00, z=209.34], EntityOtherPlayerMP['MovingA'/106, l='MpServer', x=136.76, y=62.00, z=207.78], EntityOtherPlayerMP['MovingD'/103, l='MpServer', x=138.01, y=62.00, z=209.34], EntityOtherPlayerMP['MovingA'/106, l='MpServer', x=136.76, y=62.00, z=207.78], EntitySheep['Sheep'/453483, l='MpServer', x=186.69, y=62.00, z=184.63], EntityOtherPlayerMP['Moving'/115, l='MpServer', x=140.34, y=62.00, z=202.62], EntityOtherPlayerMP['MovingC'/109, l='MpServer', x=139.62, y=62.00, z=205.62], EntityOtherPlayerMP['Standing'/118, l='MpServer', x=137.94, y=62.00, z=196.22], EntitySheep['Sheep'/453750, l='MpServer', x=189.28, y=62.00, z=184.66], EntityOtherPlayerMP['MovingB'/112, l='MpServer', x=140.31, y=62.00, z=207.96], EntityOtherPlayerMP['Moving'/115, l='MpServer', x=140.34, y=62.00, z=202.62], EntityOtherPlayerMP['Standing'/118, l='MpServer', x=137.94, y=62.00, z=196.22], EntityOtherPlayerMP['HeathB'/121, l='MpServer', x=132.50, y=62.00, z=182.38], EntityOtherPlayerMP['HeathA'/124, l='MpServer', x=132.22, y=62.00, z=188.00], EntityOtherPlayerMP['MaxRange'/127, l='MpServer', x=135.53, y=62.00, z=185.53], EntityOtherPlayerMP['MinRange'/130, l='MpServer', x=130.50, y=62.00, z=185.41], EntitySheep['Sheep'/453764, l='MpServer', x=190.72, y=62.00, z=186.59], EntityOtherPlayerMP['MovingC'/109, l='MpServer', x=139.62, y=62.00, z=205.62], EntityOtherPlayerMP['MovingB'/112, l='MpServer', x=140.31, y=62.00, z=207.96], EntityArmorStand['§6KillauraAimTest 1'/148, l='MpServer', x=190.50, y=65.66, z=170.50], EntityArmorStand['§6KillauraSwitchTest'/149, l='MpServer', x=189.50, y=65.66, z=186.50], EntityArmorStand['§6ChestStealer'/153, l='MpServer', x=200.50, y=65.66, z=195.50], EntityArmorStand['§6BedFucker'/154, l='MpServer', x=185.50, y=65.66, z=195.50], EntityArmorStand['§6KillauraWallTest'/155, l='MpServer', x=181.50, y=65.66, z=139.50], EntityArmorStand['§6PVP'/156, l='MpServer', x=181.50, y=65.66, z=160.50], EntityArmorStand['§6KillauraAimTest 2'/157, l='MpServer', x=179.50, y=65.66, z=170.50], EntityArmorStand['§6KillauraMultiTest1'/158, l='MpServer', x=179.50, y=65.66, z=186.50], EntityArmorStand['§6DamageTest'/159, l='MpServer', x=169.50, y=65.66, z=165.50], EntityArmorStand['§6KillauraMultiTest3'/160, l='MpServer', x=159.50, y=65.66, z=152.50], EntitySheep['Sheep'/453796, l='MpServer', x=190.94, y=62.00, z=185.38], EntityArmorStand['§6Velocity'/167, l='MpServer', x=155.50, y=65.66, z=165.50], EntityArmorStand['§6KillauraMultiTest2'/168, l='MpServer', x=144.50, y=65.66, z=152.50], EntityArmorStand['§6KillauraMultiTest4'/169, l='MpServer', x=147.50, y=65.66, z=139.50], EntityArmorStand['§6TNTBlock'/170, l='MpServer', x=151.50, y=65.66, z=182.50], EntityVillager['Aim10'/454070, l='MpServer', x=189.50, y=75.00, z=134.50], EntityVillager['Aim9'/415664, l='MpServer', x=184.50, y=74.00, z=134.50], EntityOtherPlayerMP['YoonDD'/454151, l='MpServer', x=164.47, y=62.00, z=179.78], EntitySheep['Sheep'/453581, l='MpServer', x=192.16, y=62.00, z=185.19], EntitySheep['Sheep'/453585, l='MpServer', x=189.47, y=62.00, z=185.63], EntityPig['Pig'/452318, l='MpServer', x=146.07, y=60.00, z=149.65], EntityPig['Pig'/452319, l='MpServer', x=147.49, y=60.00, z=149.40], EntityPig['Pig'/452326, l='MpServer', x=144.53, y=60.00, z=150.84], EntityPig['Pig'/452327, l='MpServer', x=147.50, y=60.00, z=155.53], EntityPig['Pig'/452324, l='MpServer', x=142.59, y=60.00, z=151.81], EntitySheep['Sheep'/453604, l='MpServer', x=187.94, y=62.00, z=184.19], EntityPig['Pig'/452325, l='MpServer', x=142.34, y=60.00, z=148.47], EntityPig['Pig'/452322, l='MpServer', x=141.63, y=60.00, z=150.46], EntityPig['Pig'/452323, l='MpServer', x=141.44, y=60.00, z=149.48], EntityPig['Pig'/452320, l='MpServer', x=141.44, y=60.00, z=149.69], EntityPig['Pig'/452321, l='MpServer', x=147.48, y=60.00, z=154.05], EntityPig['Pig'/452334, l='MpServer', x=143.59, y=60.00, z=148.38], EntityVillager['Aim3'/348653, l='MpServer', x=179.50, y=62.00, z=134.50], EntityPig['Pig'/452335, l='MpServer', x=148.53, y=60.00, z=150.59], EntityPig['Pig'/452332, l='MpServer', x=148.53, y=60.00, z=153.50], EntityPig['Pig'/452333, l='MpServer', x=145.07, y=60.00, z=152.96], EntityVillager['Aim4'/271855, l='MpServer', x=185.50, y=62.00, z=134.50], EntityPig['Pig'/452330, l='MpServer', x=144.22, y=60.00, z=156.31], EntityPig['Pig'/452331, l='MpServer', x=140.44, y=60.00, z=150.94], EntityPig['Pig'/452328, l='MpServer', x=148.53, y=60.00, z=151.88], EntityPig['Pig'/452329, l='MpServer', x=140.44, y=60.00, z=153.38], EntityPig['Pig'/452342, l='MpServer', x=144.66, y=60.00, z=148.44], EntityPig['Pig'/452343, l='MpServer', x=145.66, y=60.00, z=150.56], EntityPig['Pig'/452340, l='MpServer', x=140.44, y=60.00, z=150.66], EntityPig['Pig'/452341, l='MpServer', x=146.19, y=60.00, z=154.38], EntityPig['Pig'/452338, l='MpServer', x=146.38, y=60.00, z=148.44], EntityPig['Pig'/452339, l='MpServer', x=148.53, y=60.00, z=150.43], EntityPig['Pig'/452336, l='MpServer', x=142.89, y=60.00, z=154.19], EntityPig['Pig'/452337, l='MpServer', x=146.29, y=60.00, z=150.71], EntityPig['Pig'/452350, l='MpServer', x=144.69, y=60.00, z=149.50], EntityPig['Pig'/452351, l='MpServer', x=142.75, y=60.00, z=152.97], EntityPig['Pig'/452348, l='MpServer', x=145.94, y=60.00, z=153.31], EntityPig['Pig'/452349, l='MpServer', x=143.25, y=60.00, z=149.50], EntityPig['Pig'/452346, l='MpServer', x=141.69, y=60.00, z=152.03], EntityPig['Pig'/452347, l='MpServer', x=144.24, y=60.00, z=155.68], EntityPig['Pig'/452344, l='MpServer', x=146.28, y=60.00, z=152.00], EntityPig['Pig'/452345, l='MpServer', x=144.58, y=60.00, z=148.44]]
	Retry entities: 0 total; []
	Server brand: DionaSpigot (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1032550944 bytes (984 MB) / 1765801984 bytes (1684 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn614m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Glint-Colorizer{1.0} [Glint Colorizer] (minecraft.jar) 
	UCHIJA	InputFix{1.8.x-v2} [InputFix] (minecraft.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	customskinloader{14.17} [CustomSkinLoader] ([万用皮肤补丁] CustomSkinLoader_ForgeLegacy-14.17.jar) 
	UCHIJA	DJTastyMod{1.0} [DJTastyMod] ([1.8.9] DJTastyMod PORT.jar) 
	UCHIJA	FpsReducer{mc1.8.9-1.10.3} [FPS Reducer] ([FPS减速器] FpsReducer-mc1.8.9-1.10.3.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] ([泡沫修复] foamfix-0.6.3a-anarchy-1.8.x.jar) 
	UCHIJA	ias{D7.29 :P} [In-Game Account Switcher] ([游戏内账号切换] InGameAccountSwitcher-Forge-1.8-8.0.1.jar) 
	UCHIJA	camera{1.1} [Camera] (Camera-1.1-1.8.9.jar) 
	UCHIJA	damagetint{1.2} [Damage Tint] (Damage_Tint_1.2 (F).jar) 
	UCHIJA	labymod{3.9.62} [LabyMod] (LabyMod-3-1.8.9.jar) 
	UCHIJA	keystrokes{KMV5} [KeystrokesMod] (raven-XD.jar) 
	Loaded coremods (and transformers): 
MixinLoader (raven-XD.jar)
  
CustomSkinLoader ([万用皮肤补丁] CustomSkinLoader_ForgeLegacy-14.17.jar)
  customskinloader.forge.loader.LaunchWrapper
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. ([泡沫修复] foamfix-0.6.3a-anarchy-1.8.x.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CameraFMLLoadingPlugin (Camera-1.1-1.8.9.jar)
  com.oreobits.camera.EntityRendererTransformer
  com.oreobits.camera.RendererLivingEntityTransformer
  com.oreobits.camera.NetworkManagerTransformer
LabyModCoreMod (LabyMod-3-1.8.9.jar)
  net.labymod.core.asm.LabyModTransformer
  net.labymod.addons.custommainmenu.asm.CustomMainMenuTransformer
  com.tterrag.blur.BlurTransformer
  net.labymod.addons.itemphysic.asm.ItemPhysicTransformer
  net.labymod.addons.moreparticle.asm.MoreParticleTranformer
  net.labymod.addons.motionblur.asm.MotionBlurTransformer
Glint Colorizer ([1.8.9] GlintColorizer - 1.0.jar)
  me.powns.glintcolorizer.asm.itemrender.RenderItemTransformer
InputFix ([输入修正] InputFix-1.8.x-v2.jar)
  lain.mods.inputfix.InputFixTransformer
DamageTintCoreMod (Damage_Tint_1.2 (F).jar)
  me.aycy.damagetint.core.RendererTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 24.3.1.240216' Renderer: 'AMD Radeon(TM) Graphics'
	Launched Version: Labymod3
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Graphics GL version 4.6.0 Compatibility Profile Context 24.3.1.240216, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'FML,Forge'
	Type: Client (map_client.txt)
	Resource Packs: !     §3azura §8[§f16x§8].zip, monochrom overlay.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 24.3.1.240216
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
```

**Comment by TejasLamba2006** [comment]
![image](https://github.com/user-attachments/assets/0fef08a6-ce2c-4f40-b12a-4dfa6e6b11a1)
Isnt true at all

**Comment by TejasLamba2006** [comment]
![image](https://github.com/user-attachments/assets/5cfed20a-8083-4666-88ab-f056b035734e)
Its not crashing, lemme push
