### ISSUE TITLE
玩家死亡时游戏崩溃

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#679]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

不清楚是不是手机游玩的问题
概率性事件

### Repro steps

1.被击飞
2.落地造成摔落伤害，并且直接摔死

### Raven XD version

1.19

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (raven-XD.jar)
  AppleCore (AppleCore-mc1.8.9-3.1.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/23/24 9:47 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at keystrokesmod.module.impl.player.AutoPot.onRotation(AutoPot.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_AutoPot_onRotation_RotationEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at keystrokesmod.module.impl.other.RotationHandler.onPreMotion(RotationHandler.java:120)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_67_RotationHandler_onPreMotion_MoveInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.util.MovementInputFromOptions.func_78898_a(SourceFile:50)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:278)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:118)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at keystrokesmod.module.impl.player.AutoPot.onRotation(AutoPot.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_AutoPot_onRotation_RotationEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at keystrokesmod.module.impl.other.RotationHandler.onPreMotion(RotationHandler.java:120)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_67_RotationHandler_onPreMotion_MoveInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.util.MovementInputFromOptions.func_78898_a(SourceFile:50)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:278)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:118)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 95691
	Entity Name: Chenzirui_001
	Entity's Exact location: -11.70, 66.00, 1.75
	Entity's Block location: -12.00,66.00,1.00 - World: (-12,66,1), Chunk: (at 4,4,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.18, -0.08, 0.03
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
	Level name: MpServer
	All players: 7 total; [EntityPlayerSP['Chenzirui_001'/95691, l='MpServer', x=-11.70, y=66.00, z=1.75], EntityOtherPlayerMP['Bebynana'/978940, l='MpServer', x=-35.41, y=65.63, z=17.84], EntityOtherPlayerMP['JoseReyes000'/951409, l='MpServer', x=-6.86, y=68.39, z=-3.23], EntityOtherPlayerMP['Sorey2'/1001236, l='MpServer', x=1.81, y=97.91, z=2.03], EntityOtherPlayerMP['Fuimba78'/1024083, l='MpServer', x=-41.84, y=65.00, z=-1.91], EntityOtherPlayerMP['NatyQ2000'/619309, l='MpServer', x=0.63, y=82.57, z=-26.47], EntityOtherPlayerMP['rafael475'/858352, l='MpServer', x=24.40, y=67.00, z=22.89]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 224371 game time, 2000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntityOtherPlayerMP['Ryzelilxn'/979474, l='MpServer', x=37.67, y=6.22, z=25.20], EntityOtherPlayerMP['Bebynana'/978940, l='MpServer', x=-35.41, y=65.63, z=17.84], EntityOtherPlayerMP['Stein8'/983167, l='MpServer', x=-35.78, y=7.81, z=16.44], EntityOtherPlayerMP['rafael475'/858352, l='MpServer', x=24.40, y=67.00, z=22.89], EntityOtherPlayerMP['nikichus247'/1006466, l='MpServer', x=17.44, y=4.73, z=16.63], EntityOtherPlayerMP['Fuimba78'/1024083, l='MpServer', x=-41.84, y=65.00, z=-1.91], EntityOtherPlayerMP['redminotch'/998163, l='MpServer', x=-41.53, y=8.20, z=15.56], EntityOtherPlayerMP['rafael475'/858352, l='MpServer', x=37.00, y=65.06, z=19.74], EntityOtherPlayerMP['Sorey2'/1001236, l='MpServer', x=1.81, y=97.91, z=2.03], EntityOtherPlayerMP['NatyQ2000'/619309, l='MpServer', x=0.63, y=82.57, z=-26.47], EntityOtherPlayerMP['Fuimba78'/1024083, l='MpServer', x=-41.84, y=65.00, z=-1.91], EntityOtherPlayerMP['NatyQ2000'/619309, l='MpServer', x=0.63, y=82.57, z=-26.47], EntityOtherPlayerMP['JoseReyes000'/951409, l='MpServer', x=-6.86, y=68.39, z=-3.23], EntityOtherPlayerMP['Sorey2'/1001236, l='MpServer', x=1.81, y=97.91, z=2.03], EntityOtherPlayerMP['mireno44'/988403, l='MpServer', x=21.85, y=7.19, z=-11.44], EntityOtherPlayerMP['Bebynana'/978940, l='MpServer', x=-35.41, y=65.63, z=17.84], EntityOtherPlayerMP['rafael475'/858352, l='MpServer', x=24.40, y=67.00, z=22.89], EntityPlayerSP['Chenzirui_001'/95691, l='MpServer', x=-11.70, y=66.00, z=1.75], EntityOtherPlayerMP['JoseReyes000'/951409, l='MpServer', x=-6.86, y=68.39, z=-3.23]]
	Retry entities: 0 total; []
	Server brand: UniversoCraft
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version 5.10.168-android12-9-00002-gf3c080171fd5-ab10346004
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3160869272 bytes (3014 MB) / 4259315712 bytes (4062 MB) up to 4259315712 bytes (4062 MB)
	JVM Flags: 3 total; -Xbootclasspath/p:/data/user/10/com.tungsten.hmclpe/app_runtime/caciocavallo/ResConfHack.jar:/data/user/10/com.tungsten.hmclpe/app_runtime/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/data/user/10/com.tungsten.hmclpe/app_runtime/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar -Xms4096M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAAAA	ias{D7.29 :P} [In-Game Account Switcher] ([游戏内账号切换] InGameAccountSwitcher-Forge-1.8-8.0.1.jar) 
	UCHIJAAAAAA	inventoryhud{3.2.1} [Inventory HUD+] ([物品栏HUD+] InventoryHUD-1.8.9-3.2.1.jar) 
	UCHIJAAAAAA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.8.9-3.1.1.jar) 
	UCHIJAAAAAA	blockoverlay{3.0} [Block Overlay] (BlockOverLay.jar) 
	UCHIJAAAAAA	keystrokes{KMV5} [KeystrokesMod] (raven-XD.jar) 
	Loaded coremods (and transformers): 
MixinLoader (raven-XD.jar)
  
AppleCore (AppleCore-mc1.8.9-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
	Launched Version: 1.8.9
	LWJGL: 2.9.3
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
```

**Comment by chenzirui001** [comment]
我一会儿把applecore卸了试试

**Comment by chenzirui001** [comment]
新的崩溃
发生崩溃的时候invmanager正在工作（丢垃圾）
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (raven-XD.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/24/24 12:51 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at keystrokesmod.module.impl.player.AutoPot.onRotation(AutoPot.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_AutoPot_onRotation_RotationEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at keystrokesmod.module.impl.other.RotationHandler.onPreMotion(RotationHandler.java:120)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_RotationHandler_onPreMotion_MoveInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.util.MovementInputFromOptions.func_78898_a(SourceFile:50)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:278)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:118)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at keystrokesmod.module.impl.player.AutoPot.onRotation(AutoPot.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_AutoPot_onRotation_RotationEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at keystrokesmod.module.impl.other.RotationHandler.onPreMotion(RotationHandler.java:120)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_RotationHandler_onPreMotion_MoveInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.util.MovementInputFromOptions.func_78898_a(SourceFile:50)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:278)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:118)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 150306
	Entity Name: Chenzirui_001
	Entity's Exact location: -31.71, 62.00, -5.71
	Entity's Block location: -32.00,62.00,-6.00 - World: (-32,62,-6), Chunk: (at 0,3,10 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
	Level name: MpServer
	All players: 12 total; [EntityPlayerSP['Chenzirui_001'/150306, l='MpServer', x=-31.71, y=62.00, z=-5.71], EntityOtherPlayerMP['lian_2'/305746, l='MpServer', x=-39.30, y=61.98, z=-7.73], EntityOtherPlayerMP['Crizy_J'/302502, l='MpServer', x=-38.41, y=62.00, z=-7.72], EntityOtherPlayerMP['wellstrike'/306081, l='MpServer', x=-43.54, y=62.00, z=9.88], EntityOtherPlayerMP['NACHO_202'/299491, l='MpServer', x=-37.63, y=62.00, z=7.04], EntityOtherPlayerMP['elnever'/269368, l='MpServer', x=-31.56, y=62.00, z=-27.63], EntityOtherPlayerMP['axelcampeon2033'/288904, l='MpServer', x=-28.57, y=62.00, z=-29.21], EntityOtherPlayerMP['offeveningg2'/275132, l='MpServer', x=-31.34, y=62.00, z=-26.03], EntityOtherPlayerMP['AngelofDeath48'/195821, l='MpServer', x=-44.97, y=62.00, z=13.25], EntityOtherPlayerMP['SDiamantusS'/302107, l='MpServer', x=6.38, y=62.00, z=-32.34], EntityOtherPlayerMP['Erina_Nakiri'/302630, l='MpServer', x=13.31, y=62.00, z=-21.60], EntityOtherPlayerMP['IISsiriusSII'/302609, l='MpServer', x=6.16, y=62.00, z=-33.34]]
	Chunk stats: MultiplayerChunkCache: 119, 119
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 73306 game time, 2000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntitySnowball['Snowball'/307716, l='MpServer', x=-39.92, y=-43.31, z=-67.21], EntityItem['item.item.bootsIron'/307780, l='MpServer', x=-33.38, y=62.00, z=-4.15], EntityItem['item.item.chestplateIron'/307782, l='MpServer', x=-32.93, y=62.00, z=-4.42], EntityItem['item.item.chestplateChain'/307790, l='MpServer', x=-32.97, y=62.00, z=-4.50], EntityOtherPlayerMP['axelcampeon2033'/288904, l='MpServer', x=-28.57, y=62.00, z=-29.21], EntitySnowball['Snowball'/307723, l='MpServer', x=-32.12, y=-21.75, z=-68.22], EntityArrow['Arrow'/307605, l='MpServer', x=10.03, y=61.81, z=0.97], EntityOtherPlayerMP['Erina_Nakiri'/302630, l='MpServer', x=13.31, y=62.00, z=-21.60], EntityOtherPlayerMP['IISsiriusSII'/302609, l='MpServer', x=6.16, y=62.00, z=-33.34], EntityOtherPlayerMP['lian_2'/305746, l='MpServer', x=-39.30, y=61.98, z=-7.73], EntitySnowball['Snowball'/307730, l='MpServer', x=-28.44, y=-9.88, z=-67.65], EntityOtherPlayerMP['IISsiriusSII'/302609, l='MpServer', x=6.16, y=62.00, z=-33.34], EntitySnowball['Snowball'/307740, l='MpServer', x=-20.52, y=16.80, z=-62.66], EntitySnowball['Snowball'/307737, l='MpServer', x=-21.46, y=11.91, z=-63.24], EntityOtherPlayerMP['SDiamantusS'/302107, l='MpServer', x=6.38, y=62.00, z=-32.34], EntityOtherPlayerMP['Crizy_J'/302502, l='MpServer', x=-38.41, y=62.00, z=-7.72], EntityOtherPlayerMP['Erina_Nakiri'/302630, l='MpServer', x=13.31, y=62.00, z=-21.60], EntityOtherPlayerMP['SDiamantusS'/302107, l='MpServer', x=6.38, y=62.00, z=-32.34], EntityOtherPlayerMP['wellstrike'/306081, l='MpServer', x=-43.54, y=62.00, z=9.88], EntityOtherPlayerMP['NACHO_202'/299491, l='MpServer', x=-37.63, y=62.00, z=7.04], EntityPlayerSP['Chenzirui_001'/150306, l='MpServer', x=-31.71, y=62.00, z=-5.71], EntityOtherPlayerMP['lian_2'/305746, l='MpServer', x=-39.30, y=61.98, z=-7.73], EntityOtherPlayerMP['Crizy_J'/302502, l='MpServer', x=-38.41, y=62.00, z=-7.72], EntityOtherPlayerMP['wellstrike'/306081, l='MpServer', x=-43.54, y=62.00, z=9.88], EntityOtherPlayerMP['NACHO_202'/299491, l='MpServer', x=-37.63, y=62.00, z=7.04], EntityOtherPlayerMP['elnever'/269368, l='MpServer', x=-31.56, y=62.00, z=-27.63], EntityOtherPlayerMP['AngelofDeath48'/195821, l='MpServer', x=-44.97, y=62.00, z=13.25], EntityOtherPlayerMP['axelcampeon2033'/288904, l='MpServer', x=-28.57, y=62.00, z=-29.21], EntityOtherPlayerMP['offeveningg2'/275132, l='MpServer', x=-31.34, y=62.00, z=-26.03], EntityOtherPlayerMP['AngelofDeath48'/195821, l='MpServer', x=-44.97, y=62.00, z=13.25], EntityOtherPlayerMP['offeveningg2'/275132, l='MpServer', x=-31.34, y=62.00, z=-26.03], EntityArrow['Arrow'/307644, l='MpServer', x=21.38, y=62.00, z=10.13], EntityOtherPlayerMP['elnever'/269368, l='MpServer', x=-31.56, y=62.00, z=-27.63]]
	Retry entities: 0 total; []
	Server brand: UniversoCraft
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version 5.10.168-android12-9-00002-gf3c080171fd5-ab10346004
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2595142680 bytes (2474 MB) / 4258267136 bytes (4061 MB) up to 4258267136 bytes (4061 MB)
	JVM Flags: 3

**Comment by xia-mc** [comment]
下个版本修复
