### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#700]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

可能是autoheal导致的

### Repro steps

1.autoheal调成soup模式，当血量为4时触发
2.血量为4时被击杀

### Raven XD version

latest

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.10.41_Forge_1.8.9.jar)
  MixinLoader (raven-XD.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.14.1.31_Forge_1.8.9.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 8/4/24 2:38 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:432)
	at net.optifine.override.PlayerControllerOF.func_78769_a(PlayerControllerOF.java:79)
	at keystrokesmod.module.impl.player.AutoHeal.onRender(AutoHeal.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_75_AutoHeal_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:347)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1053)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:432)
	at net.optifine.override.PlayerControllerOF.func_78769_a(PlayerControllerOF.java:79)
	at keystrokesmod.module.impl.player.AutoHeal.onRender(AutoHeal.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_75_AutoHeal_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 4 total; [EntityPlayerSP['Chenzirui_001'/279, l='MpServer', x=-628.00, y=114.00, z=-307.00], EntityOtherPlayerMP['shuxue816'/2051, l='MpServer', x=-632.31, y=113.00, z=-308.91], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-650.22, y=7.44, z=-326.66], EntityOtherPlayerMP['Bard_Xue'/2050, l='MpServer', x=-628.09, y=111.50, z=-327.03]]
	Chunk stats: MultiplayerChunkCache: 120, 120
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -627.00,111.00,-286.00 - World: (-627,111,-286), Chunk: (at 13,6,2 in -40,-18; contains blocks -640,0,-288 to -625,255,-273), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 112812999 game time, 72000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 123 total; [EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-621.03, y=6.00, z=-349.34], EntityOtherPlayerMP['Bard_Xue'/852, l='MpServer', x=-625.27, y=6.41, z=-320.60], EntityOtherPlayerMP['Bard_Xue'/2050, l='MpServer', x=-628.09, y=111.50, z=-327.03], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-614.10, y=6.55, z=-330.53], EntityOtherPlayerMP['shuxue816'/2051, l='MpServer', x=-632.31, y=113.00, z=-308.91], EntityRabbit['Rabbit'/4, l='MpServer', x=-672.38, y=7.00, z=-375.59], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-605.47, y=6.00, z=-327.15], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-627.94, y=113.00, z=-314.53], EntityOtherPlayerMP['Bard_Xue'/949, l='MpServer', x=-605.02, y=7.08, z=-320.71], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-612.97, y=6.00, z=-307.50], EntityOtherPlayerMP['Bard_Xue'/1017, l='MpServer', x=-645.25, y=6.00, z=-308.56], EntityOtherPlayerMP['Bard_Xue'/470, l='MpServer', x=-619.53, y=6.00, z=-344.39], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-605.50, y=6.54, z=-340.35], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-628.31, y=113.00, z=-317.47], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-637.31, y=19.28, z=-342.53], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-599.68, y=6.66, z=-296.44], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-682.13, y=8.00, z=-254.50], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-625.78, y=6.00, z=-323.00], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-626.44, y=7.47, z=-339.78], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-693.08, y=6.07, z=-283.88], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-634.69, y=18.91, z=-342.80], EntityOtherPlayerMP['Bard_Xue'/470, l='MpServer', x=-621.39, y=7.19, z=-329.59], EntityPlayerSP['Chenzirui_001'/279, l='MpServer', x=-628.00, y=114.00, z=-307.00], EntityOtherPlayerMP['Bard_Xue'/139, l='MpServer', x=-693.13, y=5.90, z=-289.62], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-637.66, y=6.90, z=-319.95], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-609.00, y=111.50, z=-307.03], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-609.00, y=111.50, z=-307.03], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-644.69, y=6.09, z=-336.69], EntityOtherPlayerMP['Bard_Xue'/797, l='MpServer', x=-628.09, y=113.50, z=-310.13], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-634.68, y=18.86, z=-340.33], EntityOtherPlayerMP['Bard_Xue'/1022, l='MpServer', x=-637.31, y=16.79, z=-339.42], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-687.97, y=9.03, z=-312.01], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-598.85, y=7.13, z=-295.59], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-623.43, y=6.31, z=-317.45], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-661.75, y=3.00, z=-368.25], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-626.91, y=112.00, z=-321.91], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-620.21, y=6.15, z=-335.13], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-622.69, y=6.00, z=-333.59], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-673.78, y=5.00, z=-309.47], EntityOtherPlayerMP['niumahua520'/370, l='MpServer', x=-621.88, y=6.00, z=-316.27], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-664.43, y=9.78, z=-269.09], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-622.16, y=6.00, z=-317.31], EntityOtherPlayerMP['niumahua520'/370, l='MpServer', x=-628.00, y=114.00, z=-307.00], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-648.15, y=6.98, z=-309.40], EntityOtherPlayerMP['Bard_Xue'/949, l='MpServer', x=-599.92, y=6.00, z=-299.51], EntityOtherPlayerMP['Bard_Xue'/162, l='MpServer', x=-689.09, y=9.54, z=-320.76], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-636.75, y=19.00, z=-340.47], EntityOtherPlayerMP['Bard_Xue'/797, l='MpServer', x=-627.06, y=113.06, z=-302.19], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-667.30, y=5.17, z=-309.72], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-628.00, y=113.06, z=-312.53], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-652.16, y=76.54, z=-306.82], EntityOtherPlayerMP['Chenzirui_001'/-8008, l='MpServer', x=-647.39, y=6.50, z=-347.10], EntityOtherPlayerMP['Bard_Xue'/852, l='MpServer', x=-682.87, y=5.03, z=-312.71], EntityOtherPlayerMP['Bard_Xue'/852, l='MpServer', x=-606.53, y=6.45, z=-329.85], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-628.72, y=111.50, z=-325.72], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-626.31, y=123.50, z=-298.97], EntityOtherPlayerMP['Bard_Xue'/403, l='MpServer', x=-641.44, y=6.00, z=-295.31], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-644.07, y=7.91, z=-299.44], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-603.55, y=6.13, z=-359.01], EntityOtherPlayerMP['Bard_Xue'/438, l='MpServer', x=-636.22, y=7.16, z=-317.44], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-626.31, y=123.50, z=-298.97], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-659.06, y=7.99, z=-300.20], EntityOtherPlayerMP['Bard_Xue'/852, l='MpServer', x=-654.63, y=6.90, z=-301.27], EntityOtherPlayerMP['Bard_Xue'/852, l='MpServer', x=-656.54, y=6.69, z=-300.80], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-675.24, y=7.58, z=-283.14], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-639.75, y=6.09, z=-315.19], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-644.24, y=7.10, z=-322.26], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-604.38, y=6.36, z=-324.87], EntityOtherPlayerMP['command_god'/887, l='MpServer', x=-688.56, y=8.00, z=-253.41], EntityOtherPlayerMP['Bard_Xue'/949, l='MpServer', x=-642.32, y=6.00, z=-337.28], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-590.63, y=10.19, z=-379.69], EntityOtherPlayerMP['Bard_Xue'/949, l='MpServer', x=-604.58, y=9.25, z=-344.53], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-641.05, y=6.66, z=-302.15], EntityOtherPlayerMP['Bard_Xue'/328, l='MpServer', x=-662.81, y=9.04, z=-269.91], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-643.22, y=8.71, z=-334.47], EntityOtherPlayerMP['niumahua520'/491, l='MpServer', x=-624.72, y=6.69, z=-326.54], EntityOtherPlayerMP['Bard_Xue'/797, l='MpServer', x=-676.41, y=8.90, z=-260.29], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-603.81, y=6.28, z=-294.41], EntityOtherPlayerMP['command_god'/58, l='MpServer', x=-6
```

**Comment by xia-mc** [comment]
fixed in latest dev branch
