### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MaDinnerbone** [xia-mc/Raven-XD#715]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

Crashed .see crash report

### Repro steps

normally finished a game

### Raven XD version

1.24.0

### Crash report (if applicable)

```plaintext
MixinLoader (raven-XD_1.24.0.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 24-8-8 下午7:23
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at keystrokesmod.utility.Utils.getCompleteHealth(Utils.java:214)
	at keystrokesmod.module.impl.render.targetvisual.targethud.RavenTargetHUD.render(RavenTargetHUD.java:61)
	at keystrokesmod.module.impl.render.TargetHUD.render(TargetHUD.java:118)
	at keystrokesmod.module.impl.render.TargetHUD.onRender(TargetHUD.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_TargetHUD_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by xia-mc** [comment]
fixed in latest dev branch
