### ISSUE TITLE
This crash keeps happeninng

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#727]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

it just crashes the game 

### Repro steps

Don't know how to trigger it, as this crash seems to occur randomly for no specific reason (can't figure out how to trigger it, which is why removing other mods option is disabled on this report) 
Some things that have triggered this crash before: 
- Clicking "edit HUD" 
- joining a singleplayer world
- getting rodded by a player

### Raven XD version

latest

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (TNT Time-1.1 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  MixinLoader (raven-XD.jar)
  PatcherTweaker (Patcher-1.8.2 (1.8.9).jar)
  ModTweaker (Patcher-1.8.2 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 8/14/24 12:21 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at keystrokesmod.module.impl.player.AntiVoid.onAABB(AntiVoid.java:65)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_110_AntiVoid_onAABB_BlockAABBEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.block.Block.handler$zzi000$onAddCollisionBoxesToList(Block.java:2519)
	at net.minecraft.block.Block.addCollisionBoxesToList(Block.java)
	at net.minecraft.world.World.getCollisionBoxes(World.java:1325)
	at net.minecraft.entity.Entity.pushOutOfBlocks(Entity.java:1949)
	at net.minecraft.entity.item.EntityXPOrb.onUpdate(EntityXPOrb.java:91)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1862)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:700)
	at net.minecraft.world.World.updateEntity(World.java:1831)
	at net.minecraft.world.World.updateEntities(World.java:1663)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:281)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at keystrokesmod.module.impl.player.AntiVoid.onAABB(AntiVoid.java:65)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_110_AntiVoid_onAABB_BlockAABBEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.block.Block.handler$zzi000$onAddCollisionBoxesToList(Block.java:2519)
	at net.minecraft.block.Block.addCollisionBoxesToList(Block.java)
	at net.minecraft.world.World.getCollisionBoxes(World.java:1325)
	at net.minecraft.entity.Entity.pushOutOfBlocks(Entity.java:1949)
	at net.minecraft.entity.item.EntityXPOrb.onUpdate(EntityXPOrb.java:91)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1862)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:700)
	at net.minecraft.world.World.updateEntity(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: XPOrb (net.minecraft.entity.item.EntityXPOrb)
	Entity ID: 15888
	Entity Name: Experience Orb
	Entity's Exact location: -127.34, 65.00, 229.35
	Entity's Block location: -128.00,65.00,229.00 - World: (-128,65,229), Chunk: (at 0,4,5 in -8,14; contains blocks -128,0,224 to -113,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.03, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1663)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:545)

-- Affected level --
Details:
	Level name: TEST 4
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 44.00,64.00,176.00 - World: (44,64,176), Chunk: (at 12,4,0 in 2,11; contains blocks 32,0,176 to 47,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6358070 game time, 557377 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 62599 (now: false), thunder time: 68864 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:281)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 330663664 bytes (315 MB) / 1231552512 bytes (1174 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 1 total; -Xverify:none
	IntCache: cache: 11, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version      | Source                                    |
	| --------- | -------------------- | ------------ | ----------------------------------------- |
	| UCHIJAAAA | mcp                  | 9.19         | minecraft.jar                             |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar        |
	| UCHIJAAAA | Forge                | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar        |
	| UCHIJAAAA | essential            | 1.0.0        | Essential (forge_1.8.9).jar               |
	| UCHIJAAAA | altloader            | 1.0          | EasyMC-Mod-1.8.9.jar                      |
	| UCHIJAAAA | ias                  | D7.29 :P     | InGameAccountSwitcher-Forge-1.8-8.0.1.jar |
	| UCHIJAAAA | motionblurmod        | 2.1.2        | Motion Blur-2.1.2 (1.8.9).jar             |
	| UCHIJAAAA | patcher              | 1.8.2        | Patcher-1.8.2 (1.8.9).jar                 |
	| UCHIJAAAA | keystrokes           | KMV5         | raven-XD.jar                              |
	| UCHIJAAAA | text_overflow_scroll | 1.4.0        | Scrollable Tooltips-1.4 (1.8.9).jar       |
	| UCHIJAAAA | tnttime              | 1.1.0        | TNT Time-1.1 (1.8.9).jar                  |

	Loaded coremods (and transformers): 
FMLLoadingPlugin (TNT Time-1.1 (1.8.9).jar)
  club.sk1er.mods.tnttimer.forge.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
MixinLoader (raven-XD.jar)
  
PatcherTweaker (Patcher-1.8.2 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
ModTweaker (Patcher-1.8.2 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'FML,Forge'
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-22.5.11
	OpenGlRenderer: Intel(R) UHD Graphics 617
	OpenGlVendor: Intel Inc.
	CpuCount: 4
```

**Comment by xia-mc** [comment]
Fixed in latest dev branch.
