### ISSUE TITLE
随机崩溃

### ISSUE THREAD

**Issue by baka-iqboost** [xia-mc/Raven-XD#729]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

有时启动非常正常，有些时候forge加载结束后进入游戏界面会灰屏，约0.5s后闪退。
本人不会java，没什么iq，解决不了问题……

### Repro steps

1. 打开pcl启动器，选择一个含有rxd的1.8.9 forged版本
2. 禁用除了rxd以外的模组
3. 启动游戏
4. 祈祷，然后崩溃（什

### Raven XD version

2.0.0

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (raven-XD.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/15/24 6:20 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at keystrokesmod.module.impl.combat.LagRange.shouldStart(LagRange.java:49)
	at keystrokesmod.module.impl.combat.LagRange.onRender(LagRange.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_LagRange_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_391, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 459492456 bytes (438 MB) / 893386752 bytes (852 MB) up to 3758096384 bytes (3584 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn537m -Xmx3584m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	keystrokes{KMV5} [KeystrokesMod] (raven-XD.jar) 
	Loaded coremods (and transformers): 
MixinLoader (raven-XD.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4599' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: 1.8.9-Forge_11.15.1.2318
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4599, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'FML,Forge'
	Type: Client (map_client.txt)
	Resource Packs: Click [16x].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
```

**Comment by baka-iqboost** [comment]
看来主播的lagrange出问题了……

**Comment by baka-iqboost** [comment]
已找到短期解决办法：把配置文件latest.json删了

**Comment by baka-iqboost** [comment]
但是我还是希望您完善一下rxd, in order to make it a better client

**Comment by baka-iqboost** [comment]
看评论看评论看评论

**Comment by xia-mc** [comment]
下个版本会修复
